function hardware_joint_names = getHardwareJointNames(r)
%NOTEST

hardware_joint_names = {...
 'l_hip_abduct',...
 'l_hip_flex',...
 'l_knee',...
 'l_ankle_flex',...
 'l_ankle_roll',...
 'l_toe_flex',...
 'r_hip_abduct',...
 'r_hip_flex',...
 'r_knee',...
 'r_ankle_flex',...
 'r_ankle_roll',...
 'r_toe_flex'};

end
