function hardware_joint_names = getHardwareJointNames(r)
%NOTEST

hardware_joint_names = {...
 'Body_to_Left_Hip',...
 'Left_Hip_to_Top_Left_Leg',...
 'Top_Left_Leg_to_Bottom_Left_Leg',...
 'Bottom_Left_Leg_to_Left_Ankle',...
 'Left_Ankle_to_Left_Foot',...
 'Left_Foot_to_Left_Toe',...
 'Body_to_Right_Hip',...
 'Right_Hip_to_Top_Right_Leg',...
 'Top_Right_Leg_to_Bottom_Right_Leg',...
 'Bottom_Right_Leg_to_Right_Ankle',...
 'Right_Ankle_to_Right_Foot',...
 'Right_Foot_to_Right_Toe'};

end
