% make new xstar 
load /home/sam/atlasExperimental/data/atlas_fp.mat

exclude = {
    'neck_ay',...
    'r_arm_lwy',...
    'l_arm_lwy',...
    'r_arm_uwy',...
    'l_arm_uwy',...
    'r_arm_mwx',...
    'l_arm_mwx',...
    'r_arm_elx',...
    'r_arm_ely',...
    'l_arm_elx',...
    'l_arm_ely'...,
    'r_arm_shx',...
    'r_arm_shz',...
    'l_arm_shx',...
    'l_arm_shz'...
    'back_bkx',...
    'back_bky',...
    'back_bkz',...
    'r_leg_hpz',...
    'l_leg_hpz'...
    };

hardware_joint_names = {...
  'base_x',...
  'base_y',...
  'base_z',...
  'base_roll',...
  'base_pitch',...
  'base_yaw',...
  'back_bkz',...
  'back_bky',...
  'back_bkx',...
  'l_arm_shz',...
  'l_leg_hpz',...
  'l_leg_hpx',...
  'l_leg_hpy',...
  'l_leg_kny',...
  'l_leg_aky',...
  'l_leg_akx',...
  'l_arm_shx',...
  'l_arm_ely',...
  'l_arm_elx',...
  'l_arm_uwy',...
  'l_arm_mwx',...
  'l_arm_lwy',...
  'r_arm_shz',...
  'r_leg_hpz',...
  'r_leg_hpx',...
  'r_leg_hpy',...
  'r_leg_kny',...
  'r_leg_aky',...
  'r_leg_akx',...
  'r_arm_shx',...
  'r_arm_ely',...
  'r_arm_elx',...
  'r_arm_uwy',...
  'r_arm_mwx',...
  'r_arm_lwy',...
  'neck_ay'};

  %new_xstar = zeros(length(xstar)-2*length(exclude),1);
  new_xstar = zeros(0,1);
  i = 1;
  for name = hardware_joint_names
      if ~ismember(exclude,name)
          new_xstar(end+1,1) = xstar(i);
      end
      i =i+ 1;
  end
  new_xstar = vertcat(new_xstar,zeros(size(new_xstar)));
  old_xstar = xstar;
  xstar = new_xstar;  
  save /home/sam/atlasExperimental/data/atlas_exp_fp.mat xstar
  xstar = old_xstar;